# Site settings
title: Swift Segments
email: spacepyro@protonmail.com
description: A collection of thoughts, discoveries, and learnings in Swift and other languages.
show_downloads: "false"
baseurl: ""
url: "https://spacepyro.com"
twitter_username: spacepyro
github_username: croberts22
linkedin_username: croberts22
instagram_username: spacepyro
display_name: "Corey Roberts"
paginate: 5

# Build settings
remote_theme: pages-themes/midnight
theme: jekyll-theme-midnight
markdown: kramdown
plugins:
  - jekyll-feed

# Layout Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
